### ISSUE TITLE
Update style to follow new Angular Material template

### ISSUE THREAD

**Issue by GeorgDangl** [GeorgDangl/angular-material-shared#33]
https://github.com/GeorgDangl/angular-material-shared/blob/a51e777e41b772ad3b3fac7f6ec160a8d09d3d0e/src/angular-material-shared-demo/projects/angular-material-shared/src/styles/material-variables.scss#L1-L22

A new project with Angular Material looks like this:
```scss

// Custom Theming for Angular Material
// For more information: https://material.angular.io/guide/theming
@use '~@angular/material' as mat;
// Plus imports for other components in your app.

// Include the common styles for Angular Material. We include this here so that you only
// have to load a single css file for Angular Material in your app.
// Be sure that you only ever include this mixin once!
@include mat.core();

// Define the palettes for your theme using the Material Design palettes available in palette.scss
// (imported above). For each palette, you can optionally specify a default, lighter, and darker
// hue. Available color palettes: https://material.io/design/color/
$dangl-opencde-ui-primary: mat.define-palette(mat.$indigo-palette);
$dangl-opencde-ui-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);

// The warn palette is optional (defaults to red).
$dangl-opencde-ui-warn: mat.define-palette(mat.$red-palette);

// Create the theme object. A theme consists of configurations for individual
// theming systems such as "color" or "typography".
$dangl-opencde-ui-theme: mat.define-light-theme((
  color: (
    primary: $dangl-opencde-ui-primary,
    accent: $dangl-opencde-ui-accent,
    warn: $dangl-opencde-ui-warn,
  )
));

// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include mat.all-component-themes($dangl-opencde-ui-theme);

/* You can add global styles to this file, and also import other style files */

html, body { height: 100%; }
body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
```

So maybe we need to change it here in this package?
